
string(TOUPPER ${PROJECT_NAME} _UPPER_PROJECT_NAME)
set(_PROJECT_DEPENDENCY_DIR ${_UPPER_PROJECT_NAME}_DEPENDENCY_DIR)

find_package(NLopt CONFIG QUIET
  CONFIGS NLoptConfig.cmake
  PATHS $ENV{NLOPT_DIR}/${CMAKE_INSTALL_LIBDIR}/cmake
        ${${_PROJECT_DEPENDENCY_DIR}}/${CMAKE_INSTALL_LIBDIR}/cmake
        ${${_PROJECT_DEPENDENCY_DIR}}/lib/cmake
        /usr/${CMAKE_INSTALL_LIBDIR}/cmake
        ${CONAN_LIB_DIRS_CPUFEATURES}/cmake
    PATH_SUFFIXES nlopt
    NO_DEFAULT_PATH
)

find_package(NLopt CONFIG QUIET
  CONFIGS NLoptConfig.cmake
  PATHS $ENV{NLOPT_DIR}/${CMAKE_INSTALL_LIBDIR}/cmake
        ${${_PROJECT_DEPENDENCY_DIR}}/${CMAKE_INSTALL_LIBDIR}/cmake
        ${${_PROJECT_DEPENDENCY_DIR}}/lib/cmake
        /usr/${CMAKE_INSTALL_LIBDIR}/cmake
        ${CONAN_LIB_DIRS_NLOPT}/cmake
    PATH_SUFFIXES nlopt
)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NLopt REQUIRED NLOPT_INCLUDE_DIRS NLOPT_LIBRARIES)